name: Deploy branch deploy to juicelang.org

on:
    push:
        branches: [ deploy ]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deploy-action
              with:
                url: 'https://deploy.juicelang.org'
                auth-user: ${{ secrets.DEPLOY_AUTH_USER }}
                auth-password: ${{ secrets.DEPLOY_AUTH_PASSWORD }}
